apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z5p4qco0o-dotnet-basic
  janus-idp.io/tekton: z5p4qco0o-dotnet-basic
  backstage.io/kubernetes-id: z5p4qco0o-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z5p4qco0o-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
